version: '3.0'

services:
  petstore_swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: "petstore_swagger_ui"
    ports:
      - "8678:8080"
    volumes:
      - ./schema/petstore_api.yaml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml
  petstore_api_mock:
    container_name: petstore_api_mock
    image: muonsoft/openapi-mock
    volumes:
      - ./schema:/schema
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/schema/petstore_api.yaml'
      OPENAPI_MOCK_DEBUG: 1
    ports:
      - "8679:8080"
