version: '3.0'

services:
  restmarks_api_mock:
    container_name: restmarks_api_mock
    image: muonsoft/openapi-mock
    volumes:
      - ./schema:/schema
    environment:
      # OPENAPI_MOCK_SPECIFICATION_URL: 'https://raw.githubusercontent.com/robotics-4-all/se-course/master/lab4/restmarks_api.v3.yml'
      OPENAPI_MOCK_SPECIFICATION_URL: '/schema/restmarks_api_mock.yml'
      OPENAPI_MOCK_DEBUG: 1
    ports:
      - "8676:8080"
