version: '3.0'

services:
  restmarks_swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: "restmarks_swagger_ui"
    ports:
      - "8676:8080"
    volumes:
      - ./schema/restmarks_api_mock.yml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml
  restmarks_api_mock:
    container_name: restmarks_api_mock
    image: muonsoft/openapi-mock
    volumes:
      - ./schema:/schema
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/schema/restmarks_api_mock.yml'
      OPENAPI_MOCK_DEBUG: 1
    ports:
      - "8677:8080"
