version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: "se-mongodb"
    volumes:
      - type: "volume"
        source: "mongodb"
        target: "/data/db"
    networks:
      - se-network
    command: mongod

  nodered:
    image: nodered/node-red:latest
    container_name: "se-nodered"
    ports:
      - "1880:1880"
    volumes:
      - type: "volume"
        source: "nodered"
        target: "/data"
    networks:
      - se-network

volumes:
  mongodb:
  nodered:

networks:
  se-network:
    driver: bridge
